"""Add next_count to sponsor state"""

revision = '012e4121df94'
down_revision = '2912feaef0d9'
branch_labels = None
depends_on = None

from alembic import op  # noqa: E402
import sqlalchemy as sa  # noqa: E402


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club_sponsor_states', sa.Column('next_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('club_sponsor_states', 'next_count')
    # ### end Alembic commands ###
